{% set version = "7.1" %}

package:
  name: racket
  version: {{ version }}

source:
  fn: racket-{{ version }}.tar.gz
  url: https://github.com/racket/racket/archive/v{{ version }}.tar.gz
  sha256: 6fae1bcf293a8ad98c63300fe4d84cb137b823e3263ee5b45eb05f2a25d0ff7a

build:
  number: 1000
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - racket -e "\"hello world\""
    # Run tests.
    # Adapted from https://github.com/racket/racket/blob/master/.travis.yml
    - raco pkg install --auto --skip-installed racket-test db-test unstable-flonum-lib net-test
    #- raco test -l tests/racket/test
    - racket -l tests/racket/contract/all
    - raco test -l tests/json/json
    - raco test -l tests/file/main
    - raco test -l tests/net/head
    - raco test -l tests/net/uri-codec
    - raco test -l tests/net/url
    - raco test -l tests/net/url-port
    - raco test -l tests/net/encoders
    - raco test -l tests/openssl/basic
    - raco test -l tests/openssl/https
    - raco test -l tests/match/main
    - raco test -l tests/zo-path
    - raco test -l tests/xml/test
    - raco test -l tests/db/all-tests
    - raco test -c tests/stxparse

about:
  home: http://racket-lang.org/
  license: LGPL 3
  license_file: racket/src/COPYING_LESSER.txt
  summary: The Racket Programming Language

extra:
  recipe-maintainers:
    - insertinterestingnamehere
